
version: '3.4'
services:
  qdrant:
    image: qdrant/qdrant:v0.11.4
    command: ./qdrant --force-snapshot --snapshot ./snapshots/de_luther_en_st_mpnet-2022-12-07-08-28-15.snapshot:de_luther_en_st_mpnet
    ports:
      - "6333:6333"
    ulimits: # Only required for tests, as there are a lot of collections created
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - qdrant_data:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots

volumes:
  qdrant_data:
  qdrant_snapshots:

